/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountInfo {
  'accountHolderName' : string,
  'paymentChannel' : string,
  'accountNumber' : string,
}
export interface DepositRequest {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'paymentScreenshot' : ExternalBlob,
  'userId' : UserId,
  'plan' : Plan,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export interface Plan {
  'durationDays' : bigint,
  'depositAmount' : bigint,
  'planId' : bigint,
  'dailyProfit' : bigint,
}
export type ReferralCode = string;
export type Time = bigint;
export type UserId = string;
export interface UserProfile {
  'referralCode' : ReferralCode,
  'balance' : bigint,
  'referrers' : Array<ReferralCode>,
  'email' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'payoutMethod' : { 'jazzCash' : null } |
    { 'easypaisa' : null },
  'userId' : UserId,
  'timestamp' : Time,
  'accountNumber' : string,
  'amount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDepositRequest' : ActorMethod<[Principal], undefined>,
  'approveWithdrawalRequest' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canWithdraw' : ActorMethod<[], boolean>,
  'getAllDepositRequests' : ActorMethod<[], Array<[Principal, DepositRequest]>>,
  'getAllWithdrawalRequests' : ActorMethod<
    [],
    Array<[Principal, WithdrawalRequest]>
  >,
  'getAvailableBalance' : ActorMethod<[], bigint>,
  'getAvailablePlans' : ActorMethod<[], Array<Plan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepositAccountDetails' : ActorMethod<[], AccountInfo>,
  'getMaximumWithdrawalAmount' : ActorMethod<[], bigint>,
  'getMinimumWithdrawalAmount' : ActorMethod<[], bigint>,
  'getReferralTiers' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectDepositRequest' : ActorMethod<[Principal], undefined>,
  'rejectWithdrawalRequest' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDepositRequest' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'submitWithdrawalRequest' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];