/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserId = IDL.Text;
export const Plan = IDL.Record({
  'durationDays' : IDL.Nat,
  'depositAmount' : IDL.Nat,
  'planId' : IDL.Nat,
  'dailyProfit' : IDL.Nat,
});
export const Time = IDL.Int;
export const DepositRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'paymentScreenshot' : ExternalBlob,
  'userId' : UserId,
  'plan' : Plan,
  'timestamp' : Time,
});
export const WithdrawalRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'payoutMethod' : IDL.Variant({
    'jazzCash' : IDL.Null,
    'easypaisa' : IDL.Null,
  }),
  'userId' : UserId,
  'timestamp' : Time,
  'accountNumber' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ReferralCode = IDL.Text;
export const UserProfile = IDL.Record({
  'referralCode' : ReferralCode,
  'balance' : IDL.Nat,
  'referrers' : IDL.Vec(ReferralCode),
  'email' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const AccountInfo = IDL.Record({
  'accountHolderName' : IDL.Text,
  'paymentChannel' : IDL.Text,
  'accountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveDepositRequest' : IDL.Func([IDL.Principal], [], []),
  'approveWithdrawalRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canWithdraw' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, DepositRequest))],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, WithdrawalRequest))],
      ['query'],
    ),
  'getAvailableBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getAvailablePlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepositAccountDetails' : IDL.Func([], [AccountInfo], ['query']),
  'getMaximumWithdrawalAmount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMinimumWithdrawalAmount' : IDL.Func([], [IDL.Nat], ['query']),
  'getReferralTiers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectDepositRequest' : IDL.Func([IDL.Principal], [], []),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDepositRequest' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'submitWithdrawalRequest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserId = IDL.Text;
  const Plan = IDL.Record({
    'durationDays' : IDL.Nat,
    'depositAmount' : IDL.Nat,
    'planId' : IDL.Nat,
    'dailyProfit' : IDL.Nat,
  });
  const Time = IDL.Int;
  const DepositRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'paymentScreenshot' : ExternalBlob,
    'userId' : UserId,
    'plan' : Plan,
    'timestamp' : Time,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'payoutMethod' : IDL.Variant({
      'jazzCash' : IDL.Null,
      'easypaisa' : IDL.Null,
    }),
    'userId' : UserId,
    'timestamp' : Time,
    'accountNumber' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ReferralCode = IDL.Text;
  const UserProfile = IDL.Record({
    'referralCode' : ReferralCode,
    'balance' : IDL.Nat,
    'referrers' : IDL.Vec(ReferralCode),
    'email' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const AccountInfo = IDL.Record({
    'accountHolderName' : IDL.Text,
    'paymentChannel' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveDepositRequest' : IDL.Func([IDL.Principal], [], []),
    'approveWithdrawalRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canWithdraw' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, DepositRequest))],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, WithdrawalRequest))],
        ['query'],
      ),
    'getAvailableBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getAvailablePlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepositAccountDetails' : IDL.Func([], [AccountInfo], ['query']),
    'getMaximumWithdrawalAmount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMinimumWithdrawalAmount' : IDL.Func([], [IDL.Nat], ['query']),
    'getReferralTiers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectDepositRequest' : IDL.Func([IDL.Principal], [], []),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDepositRequest' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'submitWithdrawalRequest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };